version: '3.9'

services:
  biochemistry:
    image: ghcr.io/ahmedibar/lab-biochemistry:latest
    container_name: biochemistry_service
    restart: always
    env_file: ./biochemistry.env
    ports:
      - "5680:5680"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - erpnet

  hormone:
    image: ghcr.io/ahmedibar/lab-hormone:latest
    container_name: hormone_service
    restart: always
    env_file: ./hormone.env
    ports:
      - "5010:5010"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - erpnet

  urine:
    image: ghcr.io/ahmedibar/lab-urine:latest
    container_name: urine_service
    restart: always
    env_file: ./urine.env
    ports:
      - "5030:5030"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - erpnet

  cbc:
    image: ghcr.io/ahmedibar/lab-cbc:latest
    container_name: cbc_service
    restart: always
    env_file: ./cbc.env
    ports:
      - "5660:5660"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - erpnet

networks:
  erpnet:
    driver: bridge
