name: Build and Push Docker Images to GHCR

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push lab-base image
        run: |
          docker build -f base/Dockerfile.base -t ghcr.io/ahmedibar/lab-base:latest .
          docker push ghcr.io/ahmedibar/lab-base:latest

      - name: Build and push hormone image
        run: |
          docker build -t ghcr.io/ahmedibar/lab-hormone:latest ./hormone
          docker push ghcr.io/ahmedibar/lab-hormone:latest

      - name: Build and push urine image
        run: |
          docker build -t ghcr.io/ahmedibar/lab-urine:latest ./urine
          docker push ghcr.io/ahmedibar/lab-urine:latest
