name: Build and Push Docker Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push lab-base
        uses: docker/build-push-action@v5
        with:
          context: .
          file: base/Dockerfile.base
          push: true
          tags: ghcr.io/ahmedibar/lab-base:latest

      - name: Build and push hormone
        uses: docker/build-push-action@v5
        with:
          context: ./hormone
          file: ./hormone/Dockerfile
          push: true
          tags: ghcr.io/ahmedibar/lab-hormone:latest

      - name: Build and push urine
        uses: docker/build-push-action@v5
        with:
          context: ./urine
          file: ./urine/Dockerfile
          push: true
          tags: ghcr.io/ahmedibar/lab-urine:latest
