name: Build and Push Docker Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - name: lab-base
            context: .
            dockerfile: base/Dockerfile.base
          - name: lab-hormone
            context: ./hormone
            dockerfile: ./hormone/Dockerfile
          - name: lab-urine
            context: ./urine
            dockerfile: ./urine/Dockerfile
          - name: lab-cbc
            context: ./cbc
            dockerfile: ./cbc/Dockerfile
          - name: lab-biochemistry
            context: ./biochemistry
            dockerfile: ./biochemistry/Dockerfile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.service.name }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.dockerfile }}
          push: true
          tags: |
            ghcr.io/ahmedibar/${{ matrix.service.name }}:latest
            ghcr.io/ahmedibar/${{ matrix.service.name }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
